server:
  port: 8015

#Eureka 配置
eureka:
  instance:
    hostname: springcloud-eureka-8015 # Eureka 服务端的实例名称
  client:
    register-with-eureka: false  # 是否向eureka注册中心注册自己
    fetch-registry: false         # fetch-registry 如果为false，表示自己为注册中心
    service-url:      # 监控页面
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # /etc/hosts中添加如下内容：
      # 127.0.0.1     eureka8015
      # 127.0.0.1     eureka8016
      # 127.0.0.1     eureka8017
      defaultZone: http://eureka8016:8016/eureka/,http://eureka8017:8017/eureka/
